### ISSUE TITLE
Support Gradle version catalog 

### ISSUE THREAD

**Issue by alexvas** [kelloggm/checkerframework-gradle-plugin#278]
Please support gradle version catalog to specify a Checker Framework version.

### Actual behavior:

_Given_ in `gradle/libs.versions.toml`:
```toml
checker-qual = { group =  "org.checkerframework", name =  "checker-qual", version =  "3.44.0" }
```

and also in `build.gradle`:
```groovy
dependencies {
    compileOnly libs.checker.qual
    testCompileOnly libs.checker.qual
    checkerFramework libs.checker.qual
}
```

_Then_ there is a warning when gradle configuring a project:

```
No explicit dependency on the Checker Framework found, using default version 3.44.0
```

_Given_ plain string in `build.gradle`:

```groovy
dependencies {
  compileOnly 'org.checkerframework:checker-qual:3.44.0'
  testCompileOnly 'org.checkerframework:checker-qual:3.44.0'
  checkerFramework 'org.checkerframework:checker:3.44.0'
}
```

_Then_ no warning issued.

### Expected behavior:

There should be no difference specifying Checker framework version either as a plain string or via Gradle version catalog.

**Comment by kelloggm** [comment]
There are two parts of the Checker Framework that need to be specified:
* `checker-qual`, which contains only the annotation definitions. It needs to be on the compile classpath of any code that you want to typecheck, since the annotations need to be available at compile time.
* `checker`, which contains the typecheckers themselves. This should not be on the compile classpath, because it's a tool. Therefore, we have a `checkerFramework` configuration for this.

In your first example, the `gradle/libs.versions.toml` file only defines a dependency on the first of these (`checker-qual`), and the warning that you're seeing is about the second. In other words, that version catalog only specifies an _annotation version_ but not a _checker version_, so the plugin uses the default (and so you see the message about `No explicit dependency...`).

In your plain `build.gradle` example, note that the `checkerFramework` dependency's artifact id is `checker` and not `checker-qual`.

**Comment by alexvas** [comment]
My bad. Thank you. Just for the reference, working example using Gradle version catalog would be:

`gradle/libs.versions.toml`:
```toml
[versions]
checker-plugin-version = "0.6.40"
checker-framework-version = "3.44.0"

[libraries]
checker-qual = { group =  "org.checkerframework", name =  "checker-qual", version.ref =  "checker-framework-version" }
checker-framework = { group =  "org.checkerframework", name =  "checker", version.ref =  "checker-framework-version" }

[plugins]
checker-plugin = { id = "org.checkerframework", version.ref = "checker-plugin-version" }
```

and in `build.gradle`:
```groovy
plugins {
    id 'java'
    alias(libs.plugins.checker.plugin)
}

dependencies {
    compileOnly(libs.checker.qual)
    testCompileOnly(libs.checker.qual)
    checkerFramework(libs.checker.framework)
}

checkerFramework {
    checkers = [
            'org.checkerframework.checker.nullness.NullnessChecker'
    ]
}
```
